name: Far Cry VR Automated Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

  workflow_dispatch:

jobs:
  build:
    name: Build Far Cry VR
    runs-on: windows-2022

    permissions: write-all

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Setup Python (for meson)
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.x'

      - name: Install meson
        run: pip install meson ninja

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.3.261.1
          vulkan-use-cache: true
          vulkan-components: Glslang

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: Prepare MSVC devenv
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x86

      - name: Prepare dxvk build
        working-directory: "Sources/ThirdParty/dxvk"
        shell: cmd
        run: dxvkry_setup.bat

      - name: Build dxvk
        working-directory: "Sources/ThirdParty/dxvk/build"
        run: |
          msbuild dxvk.sln -m
          meson install

      - name: Build CryGame
        working-directory: "Sources/CryGame C++/Solution1"
        run: msbuild Solution1.sln /p:Configuration=Release -m

      - name: Create installer
        working-directory: installer
        shell: cmd
        run: create_installer.bat

      - name: Update Github dev release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "FarCry VR development build"
          files: |
            installer/farcry-vrmod*.exe

      - name: Create tagged Github release
        if: github.ref_type == 'tag'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "FarCry VR release ${{ github.ref_name }}"
          files: |
            installer/farcry-vrmod*.exe
